# Generated by Django 5.1.7 on 2025-03-21 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proizvod',
            old_name='naziv_prozvoda',
            new_name='naziv_proizvoda',
        ),
    ]
