# Generated by Django 5.1.7 on 2025-03-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_naziv_prozvoda_proizvod_naziv_proizvoda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proizvod',
            name='cena',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
